### ISSUE TITLE
install script not working

### ISSUE THREAD

**Issue by pedrokpp** [OdilonDamasceno/dino-zsh-theme#1]
the install script is not working, I had to manually install it

error:
```
./install: 3: [[: not found
ERROR: Please install Oh-my-zsh (https://github.com/ohmyzsh/ohmyzsh)
```
but I do have oh-my-zsh installed

any idea on how to help me with this issue? I really loved this theme (i've installed it manually, but i'm not sure how to fix it)

**Comment by OdilonDamasceno** [comment]
Run the following command and display the output:
`fc-match -a |grep 'Noto Emoji Nerd Font'`

If the command returns nothing copy the `Noto Emoji Nerd Font Complete.ttf` file to `~/.local/share/fonts` and run `fc-cache`

**Comment by pedrokpp** [comment]
my bad, I didn't set my terminal's font to that font sorry lol

ty for the support
